
export const TRAIN_TICKET_DATA_STRUCTURE = {
  tau_di: [
    {
      id: 177174,
      dm_tau_vat_ly_id: 720,
      ma_ga_di: "HNO",
      ten_ga_di: "Hà Nội",
      ma_ga_den: "SGO",
      ten_ga_den: "Sài Gòn",
      ga_di_km: 0,
      ga_den_km: 1726,
      ngay_di: "2025-08-15T06:00:00+07:00",
      ngay_den: "2025-08-16T17:35:00+07:00",
      ma_tau: "SE7",
      gio_di: "06:00:00",
      gio_den: "17:35:00",
      tong_cho_con: 91,
      tong_cho_khoa: 0,
      tong_cho_dai_hon: 0,
      ngay_xp: "2025-08-15T00:00:00+07:00",
      bang_gia_ve: [
        {
          id: 1236535,
          dm_tau_id: 177174,
          loai_cho: "AnLT1",
          ten_loai_cho: "Tầng 1, khoang có 4 giường",
          giam_gia_tg: 0,
          thue: 0,
          bao_hiem: 1,
          phi_tra: 0,
          gia_ve: 1858,
          giam_gia_pt: 0,
          loai_giam: 0,
          ty_le: 0,
          dien_giai_3: null,
          dien_giai_4: null,
          nhom_cho_web: "NAM",
          chos: 0,
        },
      ],
      dm_tau_vat_ly: null,
      danh_sach_toa_p: null,
      ngay: 15,
      hanh_trinh_id: 1470135,
      tau_xe_keys: [
        "177080",
        "6135447",
        "4252075",
        "3852833",
        "2282245",
        "3412868",
        "5362847",
        "5648965",
        "3801400",
      ],
      ngay_gio_di: "15/08 21:25",
      ngay_gio_den: "17/08 11:10",
      thoi_gian_tren_tau: null,
      co_ve_re: false,
      danh_sach_thong_bao: null,
      chon_cho_tu_dong: false,
      nhom_chos: null,
    },
  ],
  tau_ve: [
    {
      id: undefined,
      dm_tau_vat_ly_id: undefined,
      ma_ga_di: "",
      ten_ga_di: "",
      ma_ga_den: "",
      ten_ga_den: "",
      ga_di_km: 0,
      ga_den_km: 0,
      ngay_di: "",
      ngay_den: "",
      ma_tau: "",
      gio_di: "",
      gio_den: "",
      tong_cho_con: 0,
      tong_cho_khoa: 0,
      tong_cho_dai_hon: 0,
      ngay_xp: "",
      bang_gia_ve: [
        {
          id: undefined,
          dm_tau_id: undefined,
          loai_cho: "",
          ten_loai_cho: "",
          giam_gia_tg: 0,
          thue: 0,
          bao_hiem: 1,
          phi_tra: 0,
          gia_ve: 0,
          giam_gia_pt: 0,
          loai_giam: 0,
          ty_le: 0,
          dien_giai_3: null,
          dien_giai_4: null,
          nhom_cho_web: "CHUNG",
          chos: 0,
        },
      ],
      hanh_trinh_id: undefined,
      tau_xe_keys: [],
      ngay_gio_di: "",
      ngay_gio_den: "",
      thoi_gian_tren_tau: null,
      co_ve_re: false,
      chon_cho_tu_dong: false,
    },
  ],
  ma_dat_ve: "TYFLEZ",
  trang_thai_captcha: false,
  tau_di_biet_danh: null,
  tau_ve_biet_danh: null,
};