import {TravellingCarBookingType} from "@/types/rental.ts";

export const travellingCarsData: TravellingCarBookingType[] = [
    {
        id: "car-001",
        ten: "Thuê xe Sài Gòn đi Vũng Tàu",
        loai_dich_vu: "Đưa đón 1 chiều",
        loai_xe: "Ghế ngồi 4 chỗ",
        hang_xe: ["Toyota Fortuner", "Mitsubishi Xpander"],
        // so_cho: "Chở tối đa 3 khách",
        khoi_hanh: "Sài Gòn",
        diem_den: "Vũng Tàu",
        cho_toi_da: "7 khách/xe",
        ngay_trong_tuan: "T2, T3, T4, T5, T6, T7, CN",
        don_tai: [
            "Đón tại Sài Gòn",
            "Quận 1, Quận 2, Quận 3, Quận 4, Quận 5, Quận 6, Quận 7, Quận 8, Quận 10, Quận 11, Quận Phú Nhuận,Quận Bình Thạnh, Quận Gò Vấp, Quận Tân Bình, Quận Bình Tân, Quận Tân Phú, Thủ Đức",
            "+ 100k: Bình Chánh, Hóc Môn, Củ Chi, Nhà Bè, Quận 9, Quận 12",
        ],
        gio_don: "5:00-22:00",
        tra_tai: ["Trả tại Vũng Tàu", "Trung tâm Vũng Tàu"],
        gia: "2.500.000đ",
        gia_bao_gom: ["Phí xăng dầu", "Phí cầu đường", "Phí đậu xe"],
        gia_khong_bao_gom: [
            "Thuế GTGT",
            "Phí đón ngoài giờ",
            "Phí đón/trả ngoài khu vực",
            "Phí tài xế ăn ngủ tự túc",
            "Phụ thu lễ, tết",
        ],
        phu_thu: "Phụ thu tài xế ăn nghỉ tự túc: 150.000đ/ngày",
        thumbnail: "https://abrokenbackpack.com/wp-content/uploads/2021/06/advantages-and-disadvantages-of-travelling-by-car.jpg",
        images: [
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?fit=crop&w=600&h=400",
            "https://images.unsplash.com/photo-1570129477492-45c003edd2be?fit=crop&w=600&h=400",
            "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?fit=crop&w=600&h=400"
        ],
    },
    {
        id: "car-002",
        ten: "Thuê xe Hà Nội đi Hạ Long",
        loai_dich_vu: "Đưa đón 2 chiều",
        loai_xe: "Ghế ngồi 7 chỗ",
        hang_xe: ["Kia Carnival", "Ford Everest"],
        // so_cho: "Chở tối đa 6 khách",
        khoi_hanh: "Hà Nội",
        diem_den: "Hạ Long",
        cho_toi_da: "7 khách/xe",
        ngay_trong_tuan: "T2, T3, T4, T5, T6, T7, CN",
        don_tai: ["Đón tại Hà Nội", "Các quận nội thành"],
        gio_don: "6:00-21:00",
        tra_tai: ["Trả tại Hạ Long", "Trung tâm Hạ Long"],
        gia: "3.800.000đ",
        gia_bao_gom: ["Phí xăng dầu", "Phí cầu đường"],
        gia_khong_bao_gom: [
            "Thuế GTGT",
            "Phí đón ngoài giờ",
            "Phí tài xế ăn ngủ tự túc",
            "Phụ thu lễ, tết",
        ],
        phu_thu: "Phụ thu tài xế ăn nghỉ tự túc: 200.000đ/ngày",
        thumbnail: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/6b/4c/7a/travel-india-by-car-guide.jpg?w=1200&h=-1&s=1",
        images: [
            "https://hyundaimiennam.com/wp-content/uploads/2023/12/Xe-Khach-Hyundai-Universe-45-cho.jpg",
            "https://hyundaimiennam.com/wp-content/uploads/2023/12/Xe-Khach-Hyundai-Universe-45-cho.jpg",
            "https://images.unsplash.com/photo-1503376780353-7e6692767b70?fit=crop&w=600&h=400"
        ],
    },
    {
        id: "car-003",
        ten: "Thuê xe Đà Nẵng đi Hội An",
        loai_dich_vu: "Đưa đón 1 chiều",
        loai_xe: "Ghế ngồi 4 chỗ",
        hang_xe: ["Mazda 3", "Honda City"],
        // so_cho: "Chở tối đa 3 khách",
        khoi_hanh: "Đà Nẵng",
        diem_den: "Hội An",
        cho_toi_da: "4 khách/xe",
        ngay_trong_tuan: "T2, T3, T4, T5, T6, T7, CN",
        don_tai: ["Đón tại Đà Nẵng", "Trung tâm Đà Nẵng"],
        gio_don: "7:00-20:00",
        tra_tai: ["Trả tại Hội An", "Trung tâm Hội An"],
        gia: "800.000đ",
        gia_bao_gom: ["Phí xăng dầu", "Phí cầu đường"],
        gia_khong_bao_gom: ["Thuế GTGT", "Phí đón ngoài giờ", "Phụ thu lễ, tết"],
        phu_thu: "Không có",
        thumbnail: "https://vulinhauto.com/wp-content/uploads/2018/11/image013.jpg",
        images: [
            "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?fit=crop&w=600&h=400",
            "https://busmedia.vn/wp-content/uploads/2021/08/quang-cao-tren-xe-khach-unique-ooh-20.jpg",
            "https://images.unsplash.com/photo-1517142089942-ba376ce32a2e?fit=crop&w=600&h=400"
        ],
    },
    {
        id: "car-004",
        ten: "Thuê xe Cần Thơ đi Châu Đốc",
        loai_dich_vu: "Đưa đón 1 chiều",
        loai_xe: "Ghế ngồi 7 chỗ",
        hang_xe: ["Toyota Innova", "Suzuki XL7"],
        // so_cho: "Chở tối đa 6 khách",
        khoi_hanh: "Cần Thơ",
        diem_den: "Châu Đốc",
        cho_toi_da: "7 khách/xe",
        ngay_trong_tuan: "T2, T3, T4, T5, T6, T7, CN",
        don_tai: ["Đón tại Cần Thơ", "Trung tâm Cần Thơ"],
        gio_don: "6:00-19:00",
        tra_tai: ["Trả tại Châu Đốc", "Trung tâm Châu Đốc"],
        gia: "1.200.000đ",
        gia_bao_gom: ["Phí xăng dầu", "Phí cầu đường"],
        gia_khong_bao_gom: ["Thuế GTGT", "Phí đón ngoài giờ", "Phụ thu lễ, tết"],
        phu_thu: "Không có",
        thumbnail: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/6b/4c/7a/travel-india-by-car-guide.jpg?w=1200&h=-1&s=1",
        images: [
            "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?fit=crop&w=600&h=400",
            "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?fit=crop&w=600&h=400",
            "https://media-cdn.tripadvisor.com/media/photo-s/0e/9e/e3/20/bai-xe-ch-khach-c-a-xe.jpg"
        ],
    },
    {
        id: "car-005",
        ten: "Thuê xe Nha Trang đi Đà Lạt",
        loai_dich_vu: "Đưa đón 2 chiều",
        loai_xe: "Ghế ngồi 16 chỗ",
        hang_xe: ["Ford Transit", "Hyundai Solati"],
        // so_cho: "Chở tối đa 15 khách",
        khoi_hanh: "Nha Trang",
        diem_den: "Đà Lạt",
        cho_toi_da: "16 khách/xe",
        ngay_trong_tuan: "T2, T3, T4, T5, T6, T7, CN",
        don_tai: ["Đón tại Nha Trang", "Trung tâm Nha Trang"],
        gio_don: "5:00-20:00",
        tra_tai: ["Trả tại Đà Lạt", "Trung tâm Đà Lạt"],
        gia: "4.500.000đ",
        gia_bao_gom: ["Phí xăng dầu", "Phí cầu đường", "Phí đậu xe"],
        gia_khong_bao_gom: [
            "Thuế GTGT",
            "Phí đón ngoài giờ",
            "Phí tài xế ăn ngủ tự túc",
            "Phụ thu lễ, tết",
        ],
        phu_thu: "Phụ thu tài xế ăn nghỉ tự túc: 250.000đ/ngày",
        thumbnail: "https://otoansuong.vn/upload/sanpham/gia_xe/gia_xe_16_cho/xe-khach-16-cho-hyundai.jpg",
        images: [
            "https://images.unsplash.com/photo-1570129477492-45c003edd2be?fit=crop&w=600&h=400",
            "https://media-cdn.tripadvisor.com/media/photo-s/0e/9e/e3/20/bai-xe-ch-khach-c-a-xe.jpg",
            "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?fit=crop&w=600&h=400",
            "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?fit=crop&w=600&h=400",
            "https://images.unsplash.com/photo-1517142089942-ba376ce32a2e?fit=crop&w=600&h=400"
        ]
    },
];